### PR TITLE
Close database after Ace command finishes

### PR DESCRIPTION
**Pull request by benallfree**
Added this section to Ace commands...

Sample

### CODE REVIEW

**Comment by RomainLanz** [comment]
Liking it 👍

**Comment by thetutlage** [comment]
I am not in favour of it, will share an example soon, where I don’t want to close the connection after function execution

**Comment by thetutlage** [comment]
Same as @RomainLanz Liking it

**Comment by benallfree** [comment]
Maybe title it `Database connection management`?

**Comment by thetutlage** [comment]
Yeah, it will be better to add `connection` to be more explicit

**Pull request merged**
