### PR TITLE
Provide example of using old() to check for existence of session flash variable.

### PR DESCRIPTION
**Pull request by gcopley**

### CODE REVIEW

**Comment by thetutlage** [comment]
I have recently added an alias for `old` called `flashMessage`, which seems more relevant for generic messages.

For example: 

Instead of saying `{{ old('success') }}`, `{{ flashMessage('success') }}` makes more sense.

Whereas `{{ old('username') }}` for the input field makes more sense.

Ideally they both are the same methods but makes sense in different situation.

**Finally**
Can u document the other method `{{ flashMessage() }}` too?

**Comment by gcopley** [comment]
@thetutlage You're awesome. Thanks... this mill make for better code I think.

Yes, I'll work on getting the new flashMessage documented.

**Comment by thetutlage** [comment]
@gcopley Any updates?

**Comment by thetutlage** [comment]
Closing since no updates from the creator and the PR itself needs couple of additions. I will do them in a separate commit

**Pull request closed without merging**
